<?php
// Dispel Types
$spell_dispel[ 0] = 'DISPEL_NONE';
$spell_dispel[ 1] = 'DISPEL_MAGIC';
$spell_dispel[ 2] = 'DISPEL_CURSE';
$spell_dispel[ 3] = 'DISPEL_DISEASE';
$spell_dispel[ 4] = 'DISPEL_POISON';
$spell_dispel[ 5] = 'DISPEL_STEALTH';
$spell_dispel[ 6] = 'DISPEL_INVISIBILITY';
$spell_dispel[ 7] = 'DISPEL_ALL';
$spell_dispel[ 8] = 'DISPEL_SPE_NPC_ONLY';
$spell_dispel[ 9] = 'DISPEL_ENRAGE';
$spell_dispel[10] = 'DISPEL_ZG_TICKET';
$spell_dispel[11] = 'DESPEL_OLD_UNUSED';

//Spell Mechanics
$spell_mechanic[ 0] = 'MECHANIC_NONE';
$spell_mechanic[ 1] = 'MECHANIC_CHARM';
$spell_mechanic[ 2] = 'MECHANIC_DISORIENTED';
$spell_mechanic[ 3] = 'MECHANIC_DISARM';
$spell_mechanic[ 4] = 'MECHANIC_DISTRACT';
$spell_mechanic[ 5] = 'MECHANIC_FEAR';
$spell_mechanic[ 6] = 'MECHANIC_GRIP';
$spell_mechanic[ 7] = 'MECHANIC_ROOT';
$spell_mechanic[ 8] = 'MECHANIC_PACIFY';
$spell_mechanic[ 9] = 'MECHANIC_SILENCE';
$spell_mechanic[10] = 'MECHANIC_SLEEP';
$spell_mechanic[11] = 'MECHANIC_SNARE';
$spell_mechanic[12] = 'MECHANIC_STUN';
$spell_mechanic[13] = 'MECHANIC_FREEZE';
$spell_mechanic[14] = 'MECHANIC_KNOCKOUT';
$spell_mechanic[15] = 'MECHANIC_BLEED';
$spell_mechanic[16] = 'MECHANIC_BANDAGE';
$spell_mechanic[17] = 'MECHANIC_POLYMORPH';
$spell_mechanic[18] = 'MECHANIC_BANISH';
$spell_mechanic[19] = 'MECHANIC_SHIELD';
$spell_mechanic[20] = 'MECHANIC_SHACKLE';
$spell_mechanic[21] = 'MECHANIC_MOUNT';
$spell_mechanic[22] = 'MECHANIC_INFECTED';
$spell_mechanic[23] = 'MECHANIC_TURN';
$spell_mechanic[24] = 'MECHANIC_HORROR';
$spell_mechanic[25] = 'MECHANIC_INVULNERABILITY';
$spell_mechanic[26] = 'MECHANIC_INTERRUPT';
$spell_mechanic[27] = 'MECHANIC_DAZE';
$spell_mechanic[28] = 'MECHANIC_DISCOVERY';
$spell_mechanic[29] = 'MECHANIC_IMMUNE_SHIELD';
$spell_mechanic[30] = 'MECHANIC_SAPPED';
$spell_mechanic[31] = 'MECHANIC_ENRAGED';

// Spell Attributes
$spell_attr[0][ 0] = 'SPELL_ATTR_UNK0';                                     // 0
$spell_attr[0][ 1] = 'SPELL_ATTR_RANGED';                                   // 1 All ranged abilites have this flag
$spell_attr[0][ 2] = 'SPELL_ATTR_ON_NEXT_SWING_1';                          // 2 on next swing
$spell_attr[0][ 3] = 'SPELL_ATTR_UNK3';                                     // 3 not set in 3.0.3
$spell_attr[0][ 4] = 'SPELL_ATTR_UNK4';                                     // 4
$spell_attr[0][ 5] = 'SPELL_ATTR_TRADESPELL';                               // 5 trade spells, will be added by client to a sublist of profession spell
$spell_attr[0][ 6] = 'SPELL_ATTR_PASSIVE';                                  // 6 Passive spell
$spell_attr[0][ 7] = 'SPELL_ATTR_UNK7';                                     // 7 visible?
$spell_attr[0][ 8] = 'SPELL_ATTR_UNK8';                                     // 8
$spell_attr[0][ 9] = 'SPELL_ATTR_UNK9';                                     // 9
$spell_attr[0][10] = 'SPELL_ATTR_ON_NEXT_SWING_2';                          // 10 on next swing 2
$spell_attr[0][11] = 'SPELL_ATTR_UNK11';                                    // 11
$spell_attr[0][12] = 'SPELL_ATTR_DAYTIME_ONLY';                             // 12 only useable at daytime, not set in 2.4.2
$spell_attr[0][13] = 'SPELL_ATTR_NIGHT_ONLY';                               // 13 only useable at night, not set in 2.4.2
$spell_attr[0][14] = 'SPELL_ATTR_INDOORS_ONLY';                             // 14 only useable indoors, not set in 2.4.2
$spell_attr[0][15] = 'SPELL_ATTR_OUTDOORS_ONLY';                            // 15 Only useable outdoors.
$spell_attr[0][16] = 'SPELL_ATTR_NOT_SHAPESHIFT';                           // 16 Not while shapeshifted
$spell_attr[0][17] = 'SPELL_ATTR_ONLY_STEALTHED';                           // 17 Must be in stealth
$spell_attr[0][18] = 'SPELL_ATTR_UNK18';                                    // 18
$spell_attr[0][19] = 'SPELL_ATTR_LEVEL_DAMAGE_CALCULATION';                 // 19 spelldamage depends on caster level
$spell_attr[0][20] = 'SPELL_ATTR_STOP_ATTACK_TARGET';                       // 20 Stop attack after use this spell (and not begin attack if use)
$spell_attr[0][21] = 'SPELL_ATTR_IMPOSSIBLE_DODGE_PARRY_BLOCK';             // 21 Cannot be dodged/parried/blocked
$spell_attr[0][22] = 'SPELL_ATTR_UNK22';                                    // 22
$spell_attr[0][23] = 'SPELL_ATTR_UNK23';                                    // 23 castable while dead?
$spell_attr[0][24] = 'SPELL_ATTR_CASTABLE_WHILE_MOUNTED';                   // 24 castable while mounted
$spell_attr[0][25] = 'SPELL_ATTR_DISABLED_WHILE_ACTIVE';                    // 25 Activate and start cooldown after aura fade or remove summoned creature or go
$spell_attr[0][26] = 'SPELL_ATTR_UNK26';                                    // 26
$spell_attr[0][27] = 'SPELL_ATTR_CASTABLE_WHILE_SITTING';                   // 27 castable while sitting
$spell_attr[0][28] = 'SPELL_ATTR_CANT_USED_IN_COMBAT';                      // 28 Cannot be used in combat
$spell_attr[0][29] = 'SPELL_ATTR_UNAFFECTED_BY_INVULNERABILITY';            // 29 unaffected by invulnerability (hmm possible not...)
$spell_attr[0][30] = 'SPELL_ATTR_UNK30';                                    // 30 breakable by damage?
$spell_attr[0][31] = 'SPELL_ATTR_CANT_CANCEL';                              // 31 positive aura can't be canceled

$spell_attr[1][ 0] = 'SPELL_ATTR_EX_UNK0';                                  // 0
$spell_attr[1][ 1] = 'SPELL_ATTR_EX_DRAIN_ALL_POWER';                       // 1 use all power (Only paladin Lay of Hands and Bunyanize)
$spell_attr[1][ 2] = 'SPELL_ATTR_EX_CHANNELED_1';                           // 2 channeled 1
$spell_attr[1][ 3] = 'SPELL_ATTR_EX_UNK3';                                  // 3
$spell_attr[1][ 4] = 'SPELL_ATTR_EX_UNK4';                                  // 4
$spell_attr[1][ 5] = 'SPELL_ATTR_EX_NOT_BREAK_STEALTH';                     // 5 Not break stealth
$spell_attr[1][ 6] = 'SPELL_ATTR_EX_CHANNELED_2';                           // 6 channeled 2
$spell_attr[1][ 7] = 'SPELL_ATTR_EX_NEGATIVE';                              // 7
$spell_attr[1][ 8] = 'SPELL_ATTR_EX_NOT_IN_COMBAT_TARGET';                  // 8 Spell req target not to be in combat state
$spell_attr[1][ 9] = 'SPELL_ATTR_EX_UNK9';                                  // 9
$spell_attr[1][10] = 'SPELL_ATTR_EX_NO_THREAT';                             // 10 no generates threat on cast 100%
$spell_attr[1][11] = 'SPELL_ATTR_EX_UNK11';                                 // 11
$spell_attr[1][12] = 'SPELL_ATTR_EX_UNK12';                                 // 12
$spell_attr[1][13] = 'SPELL_ATTR_EX_UNK13';                                 // 13
$spell_attr[1][14] = 'SPELL_ATTR_EX_UNK14';                                 // 14
$spell_attr[1][15] = 'SPELL_ATTR_EX_DISPEL_AURAS_ON_IMMUNITY';              // 15 remove auras on immunity
$spell_attr[1][16] = 'SPELL_ATTR_EX_UNAFFECTED_BY_SCHOOL_IMMUNE';           // 16 unaffected by school immunity
$spell_attr[1][17] = 'SPELL_ATTR_EX_UNK17';                                 // 17
$spell_attr[1][18] = 'SPELL_ATTR_EX_UNK18';                                 // 18
$spell_attr[1][19] = 'SPELL_ATTR_EX_UNK19';                                 // 19
$spell_attr[1][20] = 'SPELL_ATTR_EX_REQ_TARGET_COMBO_POINTS';               // 20 Req combo points on target
$spell_attr[1][21] = 'SPELL_ATTR_EX_UNK21';                                 // 21
$spell_attr[1][22] = 'SPELL_ATTR_EX_REQ_COMBO_POINTS';                      // 22 Use combo points (in 4.x not required combo point target selected)
$spell_attr[1][23] = 'SPELL_ATTR_EX_UNK23';                                 // 23
$spell_attr[1][24] = 'SPELL_ATTR_EX_UNK24';                                 // 24 Req fishing pole??
$spell_attr[1][25] = 'SPELL_ATTR_EX_UNK25';                                 // 25
$spell_attr[1][26] = 'SPELL_ATTR_EX_UNK26';                                 // 26
$spell_attr[1][27] = 'SPELL_ATTR_EX_UNK27';                                 // 27
$spell_attr[1][28] = 'SPELL_ATTR_EX_UNK28';                                 // 28
$spell_attr[1][29] = 'SPELL_ATTR_EX_UNK29';                                 // 29
$spell_attr[1][30] = 'SPELL_ATTR_EX_UNK30';                                 // 30 overpower
$spell_attr[1][31] = 'SPELL_ATTR_EX_UNK31';                                 // 31

$spell_attr[2][ 0] = 'SPELL_ATTR_EX2_UNK0';                                 // 0
$spell_attr[2][ 1] = 'SPELL_ATTR_EX2_UNK1';                                 // 1
$spell_attr[2][ 2] = 'SPELL_ATTR_EX2_CANT_REFLECTED';                       // 2 ? used for detect can or not spell reflected
$spell_attr[2][ 3] = 'SPELL_ATTR_EX2_UNK3';                                 // 3
$spell_attr[2][ 4] = 'SPELL_ATTR_EX2_UNK4';                                 // 4
$spell_attr[2][ 5] = 'SPELL_ATTR_EX2_AUTOREPEAT_FLAG';                      // 5
$spell_attr[2][ 6] = 'SPELL_ATTR_EX2_UNK6';                                 // 6
$spell_attr[2][ 7] = 'SPELL_ATTR_EX2_UNK7';                                 // 7
$spell_attr[2][ 8] = 'SPELL_ATTR_EX2_UNK8';                                 // 8 not set in 3.0.3
$spell_attr[2][ 9] = 'SPELL_ATTR_EX2_UNK9';                                 // 9
$spell_attr[2][10] = 'SPELL_ATTR_EX2_UNK10';                                // 10
$spell_attr[2][11] = 'SPELL_ATTR_EX2_HEALTH_FUNNEL';                        // 11
$spell_attr[2][12] = 'SPELL_ATTR_EX2_UNK12';                                // 12
$spell_attr[2][13] = 'SPELL_ATTR_EX2_UNK13';                                // 13
$spell_attr[2][14] = 'SPELL_ATTR_EX2_UNK14';                                // 14
$spell_attr[2][15] = 'SPELL_ATTR_EX2_UNK15';                                // 15 not set in 3.0.3
$spell_attr[2][16] = 'SPELL_ATTR_EX2_UNK16';                                // 16
$spell_attr[2][17] = 'SPELL_ATTR_EX2_UNK17';                                // 17 Hunters Shot and Stings only have this flag
$spell_attr[2][18] = 'SPELL_ATTR_EX2_UNK18';                                // 18 Only Revive pet - possible req dead pet
$spell_attr[2][19] = 'SPELL_ATTR_EX2_NOT_NEED_SHAPESHIFT';                  // 19 does not necessarly need shapeshift
$spell_attr[2][20] = 'SPELL_ATTR_EX2_UNK20';                                // 20
$spell_attr[2][21] = 'SPELL_ATTR_EX2_DAMAGE_REDUCED_SHIELD';                // 21 for ice blocks, pala immunity buffs, priest absorb shields, but used also for other spells -> not sure!
$spell_attr[2][22] = 'SPELL_ATTR_EX2_UNK22';                                // 22
$spell_attr[2][23] = 'SPELL_ATTR_EX2_UNK23';                                // 23 Only mage Arcane Concentration have this flag
$spell_attr[2][24] = 'SPELL_ATTR_EX2_UNK24';                                // 24
$spell_attr[2][25] = 'SPELL_ATTR_EX2_UNK25';                                // 25
$spell_attr[2][26] = 'SPELL_ATTR_EX2_UNK26';                                // 26 unaffected by school immunity
$spell_attr[2][27] = 'SPELL_ATTR_EX2_UNK27';                                // 27
$spell_attr[2][28] = 'SPELL_ATTR_EX2_UNK28';                                // 28 no breaks stealth if it fails??
$spell_attr[2][29] = 'SPELL_ATTR_EX2_CANT_CRIT';                            // 29 Spell can't crit
$spell_attr[2][30] = 'SPELL_ATTR_EX2_UNK30';                                // 30
$spell_attr[2][31] = 'SPELL_ATTR_EX2_FOOD_BUFF';                            // 31 Food or Drink Buff (like Well Fed)

$spell_attr[3][ 0] = 'SPELL_ATTR_EX3_UNK0';                                 // 0
$spell_attr[3][ 1] = 'SPELL_ATTR_EX3_UNK1';                                 // 1
$spell_attr[3][ 2] = 'SPELL_ATTR_EX3_UNK2';                                 // 2
$spell_attr[3][ 3] = 'SPELL_ATTR_EX3_UNK3';                                 // 3
$spell_attr[3][ 4] = 'SPELL_ATTR_EX3_UNK4';                                 // 4 Druid Rebirth only this spell have this flag
$spell_attr[3][ 5] = 'SPELL_ATTR_EX3_UNK5';                                 // 5
$spell_attr[3][ 6] = 'SPELL_ATTR_EX3_UNK6';                                 // 6
$spell_attr[3][ 7] = 'SPELL_ATTR_EX3_UNK7';                                 // 7
$spell_attr[3][ 8] = 'SPELL_ATTR_EX3_UNK8';                                 // 8
$spell_attr[3][ 9] = 'SPELL_ATTR_EX3_UNK9';                                 // 9
$spell_attr[3][10] = 'SPELL_ATTR_EX3_MAIN_HAND';                            // 10 Main hand weapon required
$spell_attr[3][11] = 'SPELL_ATTR_EX3_BATTLEGROUND';                         // 11 Can casted only on battleground
$spell_attr[3][12] = 'SPELL_ATTR_EX3_CAST_ON_DEAD';                         // 12 target is a dead player (not every spell has this flag)
$spell_attr[3][13] = 'SPELL_ATTR_EX3_UNK13';                                // 13
$spell_attr[3][14] = 'SPELL_ATTR_EX3_UNK14';                                // 14 'Honorless Target' only this spells have this flag
$spell_attr[3][15] = 'SPELL_ATTR_EX3_UNK15';                                // 15 Auto Shoot, Shoot, Throw,  - this is autoshot flag
$spell_attr[3][16] = 'SPELL_ATTR_EX3_UNK16';                                // 16 no triggers effects that trigger on casting a spell??
$spell_attr[3][17] = 'SPELL_ATTR_EX3_NO_INITIAL_AGGRO';                     // 17 Causes no aggro if not missed
$spell_attr[3][18] = 'SPELL_ATTR_EX3_UNK18';                                // 18
$spell_attr[3][19] = 'SPELL_ATTR_EX3_UNK19';                                // 19
$spell_attr[3][20] = 'SPELL_ATTR_EX3_DEATH_PERSISTENT';                     // 20 Death persistent spells
$spell_attr[3][21] = 'SPELL_ATTR_EX3_UNK21';                                // 21
$spell_attr[3][22] = 'SPELL_ATTR_EX3_REQ_WAND';                             // 22 Req wand
$spell_attr[3][23] = 'SPELL_ATTR_EX3_UNK23';                                // 23
$spell_attr[3][24] = 'SPELL_ATTR_EX3_REQ_OFFHAND';                          // 24 Req offhand weapon
$spell_attr[3][25] = 'SPELL_ATTR_EX3_UNK25';                                // 25 no cause spell pushback ?
$spell_attr[3][26] = 'SPELL_ATTR_EX3_UNK26';                                // 26
$spell_attr[3][27] = 'SPELL_ATTR_EX3_UNK27';                                // 27
$spell_attr[3][28] = 'SPELL_ATTR_EX3_UNK28';                                // 28
$spell_attr[3][29] = 'SPELL_ATTR_EX3_UNK29';                                // 29
$spell_attr[3][30] = 'SPELL_ATTR_EX3_UNK30';                                // 30
$spell_attr[3][31] = 'SPELL_ATTR_EX3_UNK31';                                // 31

$spell_attr[4][ 0] = 'SPELL_ATTR_EX4_UNK0';                                 // 0
$spell_attr[4][ 1] = 'SPELL_ATTR_EX4_UNK1';                                 // 1 proc on finishing move?
$spell_attr[4][ 2] = 'SPELL_ATTR_EX4_UNK2';                                 // 2
$spell_attr[4][ 3] = 'SPELL_ATTR_EX4_UNK3';                                 // 3
$spell_attr[4][ 4] = 'SPELL_ATTR_EX4_UNK4';                                 // 4 This will no longer cause guards to attack on use??
$spell_attr[4][ 5] = 'SPELL_ATTR_EX4_UNK5';                                 // 5
$spell_attr[4][ 6] = 'SPELL_ATTR_EX4_NOT_STEALABLE';                        // 6 although such auras might be dispellable, they cannot be stolen
$spell_attr[4][ 7] = 'SPELL_ATTR_EX4_UNK7';                                 // 7
$spell_attr[4][ 8] = 'SPELL_ATTR_EX4_STACK_DOT_MODIFIER';                   // 8
$spell_attr[4][ 9] = 'SPELL_ATTR_EX4_UNK9';                                 // 9
$spell_attr[4][10] = 'SPELL_ATTR_EX4_SPELL_VS_EXTEND_COST';                 // 10 Rogue Shiv have this flag
$spell_attr[4][11] = 'SPELL_ATTR_EX4_UNK11';                                // 11
$spell_attr[4][12] = 'SPELL_ATTR_EX4_UNK12';                                // 12
$spell_attr[4][13] = 'SPELL_ATTR_EX4_UNK13';                                // 13
$spell_attr[4][14] = 'SPELL_ATTR_EX4_UNK14';                                // 14
$spell_attr[4][15] = 'SPELL_ATTR_EX4_UNK15';                                // 15
$spell_attr[4][16] = 'SPELL_ATTR_EX4_NOT_USABLE_IN_ARENA';                  // 16 not usable in arena
$spell_attr[4][17] = 'SPELL_ATTR_EX4_USABLE_IN_ARENA';                      // 17 usable in arena
$spell_attr[4][18] = 'SPELL_ATTR_EX4_UNK18';                                // 18
$spell_attr[4][19] = 'SPELL_ATTR_EX4_UNK19';                                // 19
$spell_attr[4][20] = 'SPELL_ATTR_EX4_UNK20';                                // 20
$spell_attr[4][21] = 'SPELL_ATTR_EX4_UNK21';                                // 21
$spell_attr[4][22] = 'SPELL_ATTR_EX4_UNK22';                                // 22
$spell_attr[4][23] = 'SPELL_ATTR_EX4_UNK23';                                // 23
$spell_attr[4][24] = 'SPELL_ATTR_EX4_UNK24';                                // 24
$spell_attr[4][25] = 'SPELL_ATTR_EX4_UNK25';                                // 25 pet scaling auras
$spell_attr[4][26] = 'SPELL_ATTR_EX4_CAST_ONLY_IN_OUTLAND';                 // 26 Can only be used in Outland.
$spell_attr[4][27] = 'SPELL_ATTR_EX4_UNK27';                                // 27
$spell_attr[4][28] = 'SPELL_ATTR_EX4_UNK28';                                // 28
$spell_attr[4][29] = 'SPELL_ATTR_EX4_UNK29';                                // 29
$spell_attr[4][30] = 'SPELL_ATTR_EX4_UNK30';                                // 30
$spell_attr[4][31] = 'SPELL_ATTR_EX4_UNK31';                                // 31

$spell_attr[5][ 0] = 'SPELL_ATTR_EX5_UNK0';                                 // 0
$spell_attr[5][ 1] = 'SPELL_ATTR_EX5_NO_REAGENT_WHILE_PREP';                // 1 not need reagents if UNIT_FLAG_PREPARATION
$spell_attr[5][ 2] = 'SPELL_ATTR_EX5_UNK2';                                 // 2
$spell_attr[5][ 3] = 'SPELL_ATTR_EX5_USABLE_WHILE_STUNNED';                 // 3 usable while stunned
$spell_attr[5][ 4] = 'SPELL_ATTR_EX5_UNK4';                                 // 4
$spell_attr[5][ 5] = 'SPELL_ATTR_EX5_SINGLE_TARGET_SPELL';                  // 5 Only one target can be apply at a time
$spell_attr[5][ 6] = 'SPELL_ATTR_EX5_UNK6';                                 // 6
$spell_attr[5][ 7] = 'SPELL_ATTR_EX5_UNK7';                                 // 7
$spell_attr[5][ 8] = 'SPELL_ATTR_EX5_UNK8';                                 // 8
$spell_attr[5][ 9] = 'SPELL_ATTR_EX5_START_PERIODIC_AT_APPLY';              // 9  begin periodic tick at aura apply
$spell_attr[5][10] = 'SPELL_ATTR_EX5_UNK10';                                // 10
$spell_attr[5][11] = 'SPELL_ATTR_EX5_UNK11';                                // 11
$spell_attr[5][12] = 'SPELL_ATTR_EX5_UNK12';                                // 12
$spell_attr[5][13] = 'SPELL_ATTR_EX5_UNK13';                                // 13
$spell_attr[5][14] = 'SPELL_ATTR_EX5_UNK14';                                // 14
$spell_attr[5][15] = 'SPELL_ATTR_EX5_UNK15';                                // 15
$spell_attr[5][16] = 'SPELL_ATTR_EX5_UNK16';                                // 16
$spell_attr[5][17] = 'SPELL_ATTR_EX5_USABLE_WHILE_FEARED';                  // 17 usable while feared
$spell_attr[5][18] = 'SPELL_ATTR_EX5_USABLE_WHILE_CONFUSED';                // 18 usable while confused
$spell_attr[5][19] = 'SPELL_ATTR_EX5_UNK19';                                // 19
$spell_attr[5][20] = 'SPELL_ATTR_EX5_UNK20';                                // 20
$spell_attr[5][21] = 'SPELL_ATTR_EX5_UNK21';                                // 21
$spell_attr[5][22] = 'SPELL_ATTR_EX5_UNK22';                                // 22
$spell_attr[5][23] = 'SPELL_ATTR_EX5_UNK23';                                // 23
$spell_attr[5][24] = 'SPELL_ATTR_EX5_UNK24';                                // 24
$spell_attr[5][25] = 'SPELL_ATTR_EX5_UNK25';                                // 25
$spell_attr[5][26] = 'SPELL_ATTR_EX5_UNK26';                                // 26
$spell_attr[5][27] = 'SPELL_ATTR_EX5_UNK27';                                // 27
$spell_attr[5][28] = 'SPELL_ATTR_EX5_UNK28';                                // 28
$spell_attr[5][29] = 'SPELL_ATTR_EX5_UNK29';                                // 29
$spell_attr[5][30] = 'SPELL_ATTR_EX5_UNK30';                                // 30
$spell_attr[5][31] = 'SPELL_ATTR_EX5_UNK31';                                // 31 Forces all nearby enemies to focus attacks caster

$spell_attr[6][ 0] = 'SPELL_ATTR_EX6_UNK0';                                 // 0 Only Move spell have this flag
$spell_attr[6][ 1] = 'SPELL_ATTR_EX6_ONLY_IN_ARENA';                        // 1 only usable in arena, not used in 3.2.0a and early
$spell_attr[6][ 2] = 'SPELL_ATTR_EX6_UNK2';                                 // 2
$spell_attr[6][ 3] = 'SPELL_ATTR_EX6_UNK3';                                 // 3
$spell_attr[6][ 4] = 'SPELL_ATTR_EX6_UNK4';                                 // 4
$spell_attr[6][ 5] = 'SPELL_ATTR_EX6_UNK5';                                 // 5
$spell_attr[6][ 6] = 'SPELL_ATTR_EX6_UNK6';                                 // 6
$spell_attr[6][ 7] = 'SPELL_ATTR_EX6_UNK7';                                 // 7
$spell_attr[6][ 8] = 'SPELL_ATTR_EX6_UNK8';                                 // 8
$spell_attr[6][ 9] = 'SPELL_ATTR_EX6_UNK9';                                 // 9
$spell_attr[6][10] = 'SPELL_ATTR_EX6_UNK10';                                // 10
$spell_attr[6][11] = 'SPELL_ATTR_EX6_NOT_IN_RAID_INSTANCE';                 // 11 not usable in raid instance
$spell_attr[6][12] = 'SPELL_ATTR_EX6_UNK12';                                // 12
$spell_attr[6][13] = 'SPELL_ATTR_EX6_UNK13';                                // 13
$spell_attr[6][14] = 'SPELL_ATTR_EX6_UNK14';                                // 14
$spell_attr[6][15] = 'SPELL_ATTR_EX6_UNK15';                                // 15 not set in 3.0.3
$spell_attr[6][16] = 'SPELL_ATTR_EX6_UNK16';                                // 16
$spell_attr[6][17] = 'SPELL_ATTR_EX6_UNK17';                                // 17
$spell_attr[6][18] = 'SPELL_ATTR_EX6_UNK18';                                // 18
$spell_attr[6][19] = 'SPELL_ATTR_EX6_UNK19';                                // 19
$spell_attr[6][20] = 'SPELL_ATTR_EX6_UNK20';                                // 20
$spell_attr[6][21] = 'SPELL_ATTR_EX6_UNK21';                                // 21
$spell_attr[6][22] = 'SPELL_ATTR_EX6_UNK22';                                // 22
$spell_attr[6][23] = 'SPELL_ATTR_EX6_UNK23';                                // 23 not set in 3.0.3
$spell_attr[6][24] = 'SPELL_ATTR_EX6_UNK24';                                // 24 not set in 3.0.3
$spell_attr[6][25] = 'SPELL_ATTR_EX6_UNK25';                                // 25 not set in 3.0.3
$spell_attr[6][26] = 'SPELL_ATTR_EX6_UNK26';                                // 26 not set in 3.0.3
$spell_attr[6][27] = 'SPELL_ATTR_EX6_UNK27';                                // 27 not set in 3.0.3
$spell_attr[6][28] = 'SPELL_ATTR_EX6_UNK28';                                // 28 not set in 3.0.3
$spell_attr[6][29] = 'SPELL_ATTR_EX6_NO_DMG_MODS';                          // 29 do not apply damage mods (usually in cases where it has already been applied)
$spell_attr[6][30] = 'SPELL_ATTR_EX6_UNK30';                                // 30 not set in 3.0.3
$spell_attr[6][31] = 'SPELL_ATTR_EX6_UNK31';                                // 31 not set in 3.0.3

$spell_attr[7][ 0] = 'SPELL_ATTR_EX7_UNK0';                                 // 0
$spell_attr[7][ 1] = 'SPELL_ATTR_EX7_UNK1';                                 // 1
$spell_attr[7][ 2] = 'SPELL_ATTR_EX7_PALADIN_AURA';                         // 2
$spell_attr[7][ 3] = 'SPELL_ATTR_EX7_UNK3';                                 // 3
$spell_attr[7][ 4] = 'SPELL_ATTR_EX7_UNK4';                                 // 4
$spell_attr[7][ 5] = 'SPELL_ATTR_EX7_TOTEM_SPELL';                          // 5  shaman summon totem spells
$spell_attr[7][ 6] = 'SPELL_ATTR_EX7_UNK6';                                 // 6
$spell_attr[7][ 7] = 'SPELL_ATTR_EX7_UNK7';                                 // 7
$spell_attr[7][ 8] = 'SPELL_ATTR_EX7_UNK8';                                 // 8
$spell_attr[7][ 9] = 'SPELL_ATTR_EX7_UNK9';                                 // 9
$spell_attr[7][10] = 'SPELL_ATTR_EX7_UNK10';                                // 10
$spell_attr[7][11] = 'SPELL_ATTR_EX7_unk11';                                // 11
$spell_attr[7][12] = 'SPELL_ATTR_EX7_UNK12';                                // 12
$spell_attr[7][13] = 'SPELL_ATTR_EX7_UNK13';                                // 13
$spell_attr[7][14] = 'SPELL_ATTR_EX7_UNK14';                                // 14
$spell_attr[7][15] = 'SPELL_ATTR_EX7_UNK15';                                // 15
$spell_attr[7][16] = 'SPELL_ATTR_EX7_UNK16';                                // 16
$spell_attr[7][17] = 'SPELL_ATTR_EX7_UNK17';                                // 17
$spell_attr[7][18] = 'SPELL_ATTR_EX7_UNK18';                                // 18
$spell_attr[7][19] = 'SPELL_ATTR_EX7_UNK19';                                // 19
$spell_attr[7][20] = 'SPELL_ATTR_EX7_UNK20';                                // 20
$spell_attr[7][21] = 'SPELL_ATTR_EX7_UNK21';                                // 21
$spell_attr[7][22] = 'SPELL_ATTR_EX7_UNK22';                                // 22
$spell_attr[7][23] = 'SPELL_ATTR_EX7_UNK23';                                // 23
$spell_attr[7][24] = 'SPELL_ATTR_EX7_UNK24';                                // 24
$spell_attr[7][25] = 'SPELL_ATTR_EX7_UNK25';                                // 25
$spell_attr[7][26] = 'SPELL_ATTR_EX7_UNK26';                                // 26
$spell_attr[7][27] = 'SPELL_ATTR_EX7_UNK27';                                // 27
$spell_attr[7][28] = 'SPELL_ATTR_EX7_UNK28';                                // 28
$spell_attr[7][29] = 'SPELL_ATTR_EX7_UNK29';                                // 29
$spell_attr[7][30] = 'SPELL_ATTR_EX7_UNK30';                                // 30
$spell_attr[7][31] = 'SPELL_ATTR_EX7_UNK31';                                // 31

// Shapeshift forms
$shapeshift_form[0x00] = 'FORM_NONE';
$shapeshift_form[0x01] = 'FORM_CAT';
$shapeshift_form[0x02] = 'FORM_TREE';
$shapeshift_form[0x03] = 'FORM_TRAVEL';
$shapeshift_form[0x04] = 'FORM_AQUA';
$shapeshift_form[0x05] = 'FORM_BEAR';
$shapeshift_form[0x06] = 'FORM_AMBIENT';
$shapeshift_form[0x07] = 'FORM_GHOUL';
$shapeshift_form[0x08] = 'FORM_DIREBEAR';
$shapeshift_form[0x0E] = 'FORM_CREATUREBEAR';
$shapeshift_form[0x0F] = 'FORM_CREATURECAT';
$shapeshift_form[0x10] = 'FORM_GHOSTWOLF';
$shapeshift_form[0x11] = 'FORM_BATTLESTANCE';
$shapeshift_form[0x12] = 'FORM_DEFENSIVESTANCE';
$shapeshift_form[0x13] = 'FORM_BERSERKERSTANCE';
$shapeshift_form[0x14] = 'FORM_TEST';
$shapeshift_form[0x15] = 'FORM_ZOMBIE';
$shapeshift_form[0x16] = 'FORM_METAMORPHOSIS';
$shapeshift_form[0x1B] = 'FORM_FLIGHT_EPIC';
$shapeshift_form[0x1C] = 'FORM_SHADOW';
$shapeshift_form[0x1D] = 'FORM_FLIGHT';
$shapeshift_form[0x1E] = 'FORM_STEALTH';
$shapeshift_form[0x1F] = 'FORM_MOONKIN';
$shapeshift_form[0x20] = 'FORM_SPIRITOFREDEMPTION';

// Aura states
$aura_state[ 1] = 'AURA_STATE_DEFENSE';
$aura_state[ 2] = 'AURA_STATE_HEALTHLESS_20_PERCENT';
$aura_state[ 3] = 'AURA_STATE_BERSERKING';
$aura_state[ 4] = 'AURA_STATE_FROZEN';
$aura_state[ 5] = 'AURA_STATE_JUDGEMENT';
$aura_state[ 6] = 'AURA_STATE_UNKNOWN6';
$aura_state[ 7] = 'AURA_STATE_HUNTER_PARRY';
$aura_state[ 7] = 'AURA_STATE_ROGUE_ATTACK_FROM_STEALTH';
$aura_state[ 7] = 'AURA_STATE_UNKNOWN7';
$aura_state[ 8] = 'AURA_STATE_UNKNOWN8';
$aura_state[ 9] = 'AURA_STATE_UNKNOWN9';
$aura_state[10] = 'AURA_STATE_WARRIOR_VICTORY_RUSH';
$aura_state[11] = 'AURA_STATE_UNKNOWN11';
$aura_state[12] = 'AURA_STATE_FAERIE_FIRE';
$aura_state[13] = 'AURA_STATE_HEALTHLESS_35_PERCENT';
$aura_state[14] = 'AURA_STATE_CONFLAGRATE';
$aura_state[15] = 'AURA_STATE_SWIFTMEND';
$aura_state[16] = 'AURA_STATE_DEADLY_POISON';
$aura_state[17] = 'AURA_STATE_ENRAGE';
$aura_state[18] = 'AURA_STATE_UNKNOWN18';
$aura_state[19] = 'AURA_STATE_UNKNOWN19';
$aura_state[20] = 'AURA_STATE_UNKNOWN20';
$aura_state[21] = 'AURA_STATE_UNKNOWN21';
$aura_state[22] = 'AURA_STATE_UNKNOWN22';
$aura_state[23] = 'AURA_STATE_HEALTH_ABOVE_75_PERCENT';

// Spell Proc Flags
$spell_proc[ 0] = 'PROC_FLAG_KILLED';
$spell_proc[ 1] = 'PROC_FLAG_KILL';
$spell_proc[ 2] = 'PROC_FLAG_SUCCESSFUL_MELEE_HIT';
$spell_proc[ 3] = 'PROC_FLAG_TAKEN_MELEE_HIT';
$spell_proc[ 4] = 'PROC_FLAG_SUCCESSFUL_MELEE_SPELL_HIT';
$spell_proc[ 5] = 'PROC_FLAG_TAKEN_MELEE_SPELL_HIT';
$spell_proc[ 6] = 'PROC_FLAG_SUCCESSFUL_RANGED_HIT';
$spell_proc[ 7] = 'PROC_FLAG_TAKEN_RANGED_HIT';
$spell_proc[ 8] = 'PROC_FLAG_SUCCESSFUL_RANGED_SPELL_HIT';
$spell_proc[ 9] = 'PROC_FLAG_TAKEN_RANGED_SPELL_HIT';
$spell_proc[10] = 'PROC_FLAG_SUCCESSFUL_POSITIVE_AOE_HIT';
$spell_proc[11] = 'PROC_FLAG_TAKEN_POSITIVE_AOE';
$spell_proc[12] = 'PROC_FLAG_SUCCESSFUL_AOE_SPELL_HIT';
$spell_proc[13] = 'PROC_FLAG_TAKEN_AOE_SPELL_HIT';
$spell_proc[14] = 'PROC_FLAG_SUCCESSFUL_POSITIVE_SPELL';
$spell_proc[15] = 'PROC_FLAG_TAKEN_POSITIVE_SPELL';
$spell_proc[16] = 'PROC_FLAG_SUCCESSFUL_NEGATIVE_SPELL_HIT';
$spell_proc[17] = 'PROC_FLAG_TAKEN_NEGATIVE_SPELL_HIT';
$spell_proc[18] = 'PROC_FLAG_ON_DO_PERIODIC';
$spell_proc[19] = 'PROC_FLAG_ON_TAKE_PERIODIC';
$spell_proc[20] = 'PROC_FLAG_TAKEN_ANY_DAMAGE';
$spell_proc[21] = 'PROC_FLAG_ON_TRAP_ACTIVATION';
$spell_proc[22] = 'PROC_FLAG_TAKEN_OFFHAND_HIT';
$spell_proc[23] = 'PROC_FLAG_SUCCESSFUL_OFFHAND_HIT';
$spell_proc[24] = 'PROC_FLAG_ON_UNIT_DEATH';

// Power types
$power_type[0] = 'POWER_MANA';
$power_type[1] = 'POWER_RAGE';
$power_type[2] = 'POWER_FOCUS';
$power_type[3] = 'POWER_ENERGY';
$power_type[4] = 'POWER_HAPPINESS';
$power_type[5] = 'POWER_RUNE';
$power_type[6] = 'POWER_RUNIC_POWER';
$power_type[0xFFFFFFFE] = 'POWER_HEALTH';

// Spell Effects
$spell_effect[  1] = 'SPELL_EFFECT_INSTAKILL';
$spell_effect[  2] = 'SPELL_EFFECT_SCHOOL_DAMAGE';
$spell_effect[  3] = 'SPELL_EFFECT_DUMMY';
$spell_effect[  4] = 'SPELL_EFFECT_PORTAL_TELEPORT';
$spell_effect[  5] = 'SPELL_EFFECT_TELEPORT_UNITS';
$spell_effect[  6] = 'SPELL_EFFECT_APPLY_AURA';
$spell_effect[  7] = 'SPELL_EFFECT_ENVIRONMENTAL_DAMAGE';
$spell_effect[  8] = 'SPELL_EFFECT_POWER_DRAIN';
$spell_effect[  9] = 'SPELL_EFFECT_HEALTH_LEECH';
$spell_effect[ 10] = 'SPELL_EFFECT_HEAL';
$spell_effect[ 11] = 'SPELL_EFFECT_BIND';
$spell_effect[ 12] = 'SPELL_EFFECT_PORTAL';
$spell_effect[ 13] = 'SPELL_EFFECT_RITUAL_BASE';
$spell_effect[ 14] = 'SPELL_EFFECT_RITUAL_SPECIALIZE';
$spell_effect[ 15] = 'SPELL_EFFECT_RITUAL_ACTIVATE_PORTAL';
$spell_effect[ 16] = 'SPELL_EFFECT_QUEST_COMPLETE';
$spell_effect[ 17] = 'SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL';
$spell_effect[ 18] = 'SPELL_EFFECT_RESURRECT';
$spell_effect[ 19] = 'SPELL_EFFECT_ADD_EXTRA_ATTACKS';
$spell_effect[ 20] = 'SPELL_EFFECT_DODGE';
$spell_effect[ 21] = 'SPELL_EFFECT_EVADE';
$spell_effect[ 22] = 'SPELL_EFFECT_PARRY';
$spell_effect[ 23] = 'SPELL_EFFECT_BLOCK';
$spell_effect[ 24] = 'SPELL_EFFECT_CREATE_ITEM';
$spell_effect[ 25] = 'SPELL_EFFECT_WEAPON';
$spell_effect[ 26] = 'SPELL_EFFECT_DEFENSE';
$spell_effect[ 27] = 'SPELL_EFFECT_PERSISTENT_AREA_AURA';
$spell_effect[ 28] = 'SPELL_EFFECT_SUMMON';
$spell_effect[ 29] = 'SPELL_EFFECT_LEAP';
$spell_effect[ 30] = 'SPELL_EFFECT_ENERGIZE';
$spell_effect[ 31] = 'SPELL_EFFECT_WEAPON_PERCENT_DAMAGE';
$spell_effect[ 32] = 'SPELL_EFFECT_TRIGGER_MISSILE';
$spell_effect[ 33] = 'SPELL_EFFECT_OPEN_LOCK';
$spell_effect[ 34] = 'SPELL_EFFECT_SUMMON_CHANGE_ITEM';
$spell_effect[ 35] = 'SPELL_EFFECT_APPLY_AREA_AURA_PARTY';
$spell_effect[ 36] = 'SPELL_EFFECT_LEARN_SPELL';
$spell_effect[ 37] = 'SPELL_EFFECT_SPELL_DEFENSE';
$spell_effect[ 38] = 'SPELL_EFFECT_DISPEL';
$spell_effect[ 39] = 'SPELL_EFFECT_LANGUAGE';
$spell_effect[ 40] = 'SPELL_EFFECT_DUAL_WIELD';
$spell_effect[ 41] = 'SPELL_EFFECT_JUMP';
$spell_effect[ 42] = 'SPELL_EFFECT_JUMP2';
$spell_effect[ 43] = 'SPELL_EFFECT_TELEPORT_UNITS_FACE_CASTER';
$spell_effect[ 44] = 'SPELL_EFFECT_SKILL_STEP';
$spell_effect[ 45] = 'SPELL_EFFECT_ADD_HONOR';
$spell_effect[ 46] = 'SPELL_EFFECT_SPAWN';
$spell_effect[ 47] = 'SPELL_EFFECT_TRADE_SKILL';
$spell_effect[ 48] = 'SPELL_EFFECT_STEALTH';
$spell_effect[ 49] = 'SPELL_EFFECT_DETECT';
$spell_effect[ 50] = 'SPELL_EFFECT_TRANS_DOOR';
$spell_effect[ 51] = 'SPELL_EFFECT_FORCE_CRITICAL_HIT';
$spell_effect[ 52] = 'SPELL_EFFECT_GUARANTEE_HIT';
$spell_effect[ 53] = 'SPELL_EFFECT_ENCHANT_ITEM';
$spell_effect[ 54] = 'SPELL_EFFECT_ENCHANT_ITEM_TEMPORARY';
$spell_effect[ 55] = 'SPELL_EFFECT_TAMECREATURE';
$spell_effect[ 56] = 'SPELL_EFFECT_SUMMON_PET';
$spell_effect[ 57] = 'SPELL_EFFECT_LEARN_PET_SPELL';
$spell_effect[ 58] = 'SPELL_EFFECT_WEAPON_DAMAGE';
$spell_effect[ 59] = 'SPELL_EFFECT_CREATE_RANDOM_ITEM';
$spell_effect[ 60] = 'SPELL_EFFECT_PROFICIENCY';
$spell_effect[ 61] = 'SPELL_EFFECT_SEND_EVENT';
$spell_effect[ 62] = 'SPELL_EFFECT_POWER_BURN';
$spell_effect[ 63] = 'SPELL_EFFECT_THREAT';
$spell_effect[ 64] = 'SPELL_EFFECT_TRIGGER_SPELL';
$spell_effect[ 65] = 'SPELL_EFFECT_APPLY_AREA_AURA_RAID';
$spell_effect[ 66] = 'SPELL_EFFECT_CREATE_MANA_GEM';
$spell_effect[ 67] = 'SPELL_EFFECT_HEAL_MAX_HEALTH';
$spell_effect[ 68] = 'SPELL_EFFECT_INTERRUPT_CAST';
$spell_effect[ 69] = 'SPELL_EFFECT_DISTRACT';
$spell_effect[ 70] = 'SPELL_EFFECT_PULL';
$spell_effect[ 71] = 'SPELL_EFFECT_PICKPOCKET';
$spell_effect[ 72] = 'SPELL_EFFECT_ADD_FARSIGHT';
$spell_effect[ 73] = 'SPELL_EFFECT_UNTRAIN_TALENTS';
$spell_effect[ 74] = 'SPELL_EFFECT_APPLY_GLYPH';
$spell_effect[ 75] = 'SPELL_EFFECT_HEAL_MECHANICAL';
$spell_effect[ 76] = 'SPELL_EFFECT_SUMMON_OBJECT_WILD';
$spell_effect[ 77] = 'SPELL_EFFECT_SCRIPT_EFFECT';
$spell_effect[ 78] = 'SPELL_EFFECT_ATTACK';
$spell_effect[ 79] = 'SPELL_EFFECT_SANCTUARY';
$spell_effect[ 80] = 'SPELL_EFFECT_ADD_COMBO_POINTS';
$spell_effect[ 81] = 'SPELL_EFFECT_CREATE_HOUSE';
$spell_effect[ 82] = 'SPELL_EFFECT_BIND_SIGHT';
$spell_effect[ 83] = 'SPELL_EFFECT_DUEL';
$spell_effect[ 84] = 'SPELL_EFFECT_STUCK';
$spell_effect[ 85] = 'SPELL_EFFECT_SUMMON_PLAYER';
$spell_effect[ 86] = 'SPELL_EFFECT_ACTIVATE_OBJECT';
$spell_effect[ 87] = 'SPELL_EFFECT_WMO_DAMAGE';
$spell_effect[ 88] = 'SPELL_EFFECT_WMO_REPAIR';
$spell_effect[ 89] = 'SPELL_EFFECT_WMO_CHANGE';
$spell_effect[ 90] = 'SPELL_EFFECT_KILL_CREDIT';
$spell_effect[ 91] = 'SPELL_EFFECT_THREAT_ALL';
$spell_effect[ 92] = 'SPELL_EFFECT_ENCHANT_HELD_ITEM';
$spell_effect[ 93] = 'SPELL_EFFECT_SUMMON_PHANTASM';
$spell_effect[ 94] = 'SPELL_EFFECT_SELF_RESURRECT';
$spell_effect[ 95] = 'SPELL_EFFECT_SKINNING';
$spell_effect[ 96] = 'SPELL_EFFECT_CHARGE';
$spell_effect[ 97] = 'SPELL_EFFECT_CAST_BUTTONS';
$spell_effect[ 98] = 'SPELL_EFFECT_KNOCK_BACK';
$spell_effect[ 99] = 'SPELL_EFFECT_DISENCHANT';
$spell_effect[100] = 'SPELL_EFFECT_INEBRIATE';
$spell_effect[101] = 'SPELL_EFFECT_FEED_PET';
$spell_effect[102] = 'SPELL_EFFECT_DISMISS_PET';
$spell_effect[103] = 'SPELL_EFFECT_REPUTATION';
$spell_effect[104] = 'SPELL_EFFECT_SUMMON_OBJECT_SLOT1';
$spell_effect[105] = 'SPELL_EFFECT_SUMMON_OBJECT_SLOT2';
$spell_effect[106] = 'SPELL_EFFECT_SUMMON_OBJECT_SLOT3';
$spell_effect[107] = 'SPELL_EFFECT_SUMMON_OBJECT_SLOT4';
$spell_effect[108] = 'SPELL_EFFECT_DISPEL_MECHANIC';
$spell_effect[109] = 'SPELL_EFFECT_SUMMON_DEAD_PET';
$spell_effect[110] = 'SPELL_EFFECT_DESTROY_ALL_TOTEMS';
$spell_effect[111] = 'SPELL_EFFECT_DURABILITY_DAMAGE';
$spell_effect[112] = 'SPELL_EFFECT_112';
$spell_effect[113] = 'SPELL_EFFECT_RESURRECT_NEW';
$spell_effect[114] = 'SPELL_EFFECT_ATTACK_ME';
$spell_effect[115] = 'SPELL_EFFECT_DURABILITY_DAMAGE_PCT';
$spell_effect[116] = 'SPELL_EFFECT_SKIN_PLAYER_CORPSE';
$spell_effect[117] = 'SPELL_EFFECT_SPIRIT_HEAL';
$spell_effect[118] = 'SPELL_EFFECT_SKILL';
$spell_effect[119] = 'SPELL_EFFECT_APPLY_AREA_AURA_PET';
$spell_effect[120] = 'SPELL_EFFECT_TELEPORT_GRAVEYARD';
$spell_effect[121] = 'SPELL_EFFECT_NORMALIZED_WEAPON_DMG';
$spell_effect[122] = 'SPELL_EFFECT_122';
$spell_effect[123] = 'SPELL_EFFECT_SEND_TAXI';
$spell_effect[124] = 'SPELL_EFFECT_PLAYER_PULL';
$spell_effect[125] = 'SPELL_EFFECT_MODIFY_THREAT_PERCENT';
$spell_effect[126] = 'SPELL_EFFECT_STEAL_BENEFICIAL_BUFF';
$spell_effect[127] = 'SPELL_EFFECT_PROSPECTING';
$spell_effect[128] = 'SPELL_EFFECT_APPLY_AREA_AURA_FRIEND';
$spell_effect[129] = 'SPELL_EFFECT_APPLY_AREA_AURA_ENEMY';
$spell_effect[130] = 'SPELL_EFFECT_REDIRECT_THREAT';
$spell_effect[131] = 'SPELL_EFFECT_131';
$spell_effect[132] = 'SPELL_EFFECT_PLAY_MUSIC';
$spell_effect[133] = 'SPELL_EFFECT_UNLEARN_SPECIALIZATION';
$spell_effect[134] = 'SPELL_EFFECT_KILL_CREDIT2';
$spell_effect[135] = 'SPELL_EFFECT_CALL_PET';
$spell_effect[136] = 'SPELL_EFFECT_HEAL_PCT';
$spell_effect[137] = 'SPELL_EFFECT_ENERGIZE_PCT';
$spell_effect[138] = 'SPELL_EFFECT_LEAP_BACK';
$spell_effect[139] = 'SPELL_EFFECT_CLEAR_QUEST';
$spell_effect[140] = 'SPELL_EFFECT_FORCE_CAST';
$spell_effect[141] = 'SPELL_EFFECT_141';
$spell_effect[142] = 'SPELL_EFFECT_TRIGGER_SPELL_WITH_VALUE';
$spell_effect[143] = 'SPELL_EFFECT_APPLY_AREA_AURA_OWNER';
$spell_effect[144] = 'SPELL_EFFECT_144';
$spell_effect[145] = 'SPELL_EFFECT_145';
$spell_effect[146] = 'SPELL_EFFECT_ACTIVATE_RUNE';
$spell_effect[147] = 'SPELL_EFFECT_QUEST_FAIL';
$spell_effect[148] = 'SPELL_EFFECT_148';
$spell_effect[149] = 'SPELL_EFFECT_149';
$spell_effect[150] = 'SPELL_EFFECT_150';
$spell_effect[151] = 'SPELL_EFFECT_TRIGGER_SPELL_2';
$spell_effect[152] = 'SPELL_EFFECT_152';
$spell_effect[153] = 'SPELL_EFFECT_153';
$spell_effect[154] = 'SPELL_EFFECT_154';
$spell_effect[155] = 'SPELL_EFFECT_TITAN_GRIP';
$spell_effect[156] = 'SPELL_EFFECT_ENCHANT_ITEM_PRISMATIC';
$spell_effect[157] = 'SPELL_EFFECT_CREATE_ITEM_2';
$spell_effect[158] = 'SPELL_EFFECT_MILLING';
$spell_effect[159] = 'SPELL_EFFECT_ALLOW_RENAME_PET';
$spell_effect[160] = 'SPELL_EFFECT_160';
$spell_effect[161] = 'SPELL_EFFECT_TALENT_SPEC_COUNT';
$spell_effect[162] = 'SPELL_EFFECT_TALENT_SPEC_SELECT';

// Spell Targets
$spell_target[  1] = 'TARGET_SELF';
$spell_target[  2] = 'TARGET_RANDOM_ENEMY_CHAIN_IN_AREA';
$spell_target[  3] = 'TARGET_RANDOM_FRIEND_CHAIN_IN_AREA';
$spell_target[  5] = 'TARGET_PET';
$spell_target[  6] = 'TARGET_CHAIN_DAMAGE';
$spell_target[  7] = 'TARGET_AREAEFFECT_INSTANT';
$spell_target[  8] = 'TARGET_AREAEFFECT_CUSTOM';
$spell_target[  9] = 'TARGET_INNKEEPER_COORDINATES';
$spell_target[ 15] = 'TARGET_ALL_ENEMY_IN_AREA';
$spell_target[ 16] = 'TARGET_ALL_ENEMY_IN_AREA_INSTANT';
$spell_target[ 17] = 'TARGET_TABLE_X_Y_Z_COORDINATES';
$spell_target[ 18] = 'TARGET_EFFECT_SELECT';
$spell_target[ 20] = 'TARGET_ALL_PARTY_AROUND_CASTER';
$spell_target[ 21] = 'TARGET_SINGLE_FRIEND';
$spell_target[ 22] = 'TARGET_CASTER_COORDINATES';
$spell_target[ 23] = 'TARGET_GAMEOBJECT';
$spell_target[ 24] = 'TARGET_IN_FRONT_OF_CASTER';
$spell_target[ 25] = 'TARGET_DUELVSPLAYER';
$spell_target[ 26] = 'TARGET_GAMEOBJECT_ITEM';
$spell_target[ 27] = 'TARGET_MASTER';
$spell_target[ 28] = 'TARGET_ALL_ENEMY_IN_AREA_CHANNELED';
$spell_target[ 30] = 'TARGET_ALL_FRIENDLY_UNITS_AROUND_CASTER';
$spell_target[ 31] = 'TARGET_ALL_FRIENDLY_UNITS_IN_AREA';
$spell_target[ 32] = 'TARGET_MINION';
$spell_target[ 33] = 'TARGET_ALL_PARTY';
$spell_target[ 34] = 'TARGET_ALL_PARTY_AROUND_CASTER_2';
$spell_target[ 35] = 'TARGET_SINGLE_PARTY';
$spell_target[ 36] = 'TARGET_ALL_HOSTILE_UNITS_AROUND_CASTER';
$spell_target[ 37] = 'TARGET_AREAEFFECT_PARTY';
$spell_target[ 38] = 'TARGET_SCRIPT';
$spell_target[ 39] = 'TARGET_SELF_FISHING';
$spell_target[ 40] = 'TARGET_FOCUS_OR_SCRIPTED_GAMEOBJECT';
$spell_target[ 41] = 'TARGET_TOTEM_EARTH';
$spell_target[ 42] = 'TARGET_TOTEM_WATER';
$spell_target[ 43] = 'TARGET_TOTEM_AIR';
$spell_target[ 44] = 'TARGET_TOTEM_FIRE';
$spell_target[ 45] = 'TARGET_CHAIN_HEAL';
$spell_target[ 46] = 'TARGET_SCRIPT_COORDINATES';
$spell_target[ 47] = 'TARGET_DYNAMIC_OBJECT_FRONT';
$spell_target[ 48] = 'TARGET_SUMMON';
$spell_target[ 49] = 'TARGET_DYNAMIC_OBJECT_LEFT_SIDE';
$spell_target[ 50] = 'TARGET_DYNAMIC_OBJECT_RIGHT_SIDE';
$spell_target[ 52] = 'TARGET_AREAEFFECT_CUSTOM_2';
$spell_target[ 53] = 'TARGET_CURRENT_ENEMY_COORDINATES';
$spell_target[ 54] = 'TARGET_LARGE_FRONTAL_CONE';
$spell_target[ 56] = 'TARGET_ALL_RAID_AROUND_CASTER';
$spell_target[ 57] = 'TARGET_SINGLE_FRIEND_2';
$spell_target[ 60] = 'TARGET_NARROW_FRONTAL_CONE';
$spell_target[ 61] = 'TARGET_AREAEFFECT_PARTY_AND_CLASS';
$spell_target[ 63] = 'TARGET_DUELVSPLAYER_COORDINATES';
$spell_target[ 64] = 'TARGET_INFRONT_OF_VICTIM';
$spell_target[ 65] = 'TARGET_BEHIND_VICTIM';
$spell_target[ 66] = 'TARGET_RIGHT_FROM_VICTIM';
$spell_target[ 67] = 'TARGET_LEFT_FROM_VICTIM';
$spell_target[ 72] = 'TARGET_RANDOM_NEARBY_LOC';
$spell_target[ 73] = 'TARGET_RANDOM_CIRCUMFERENCE_POINT';
$spell_target[ 76] = 'TARGET_DYNAMIC_OBJECT_COORDINATES';
$spell_target[ 77] = 'TARGET_SINGLE_ENEMY';
$spell_target[ 78] = 'TARGET_POINT_AT_NORTH';
$spell_target[ 79] = 'TARGET_POINT_AT_SOUTH';
$spell_target[ 80] = 'TARGET_POINT_AT_EAST';
$spell_target[ 81] = 'TARGET_POINT_AT_WEST';
$spell_target[ 82] = 'TARGET_POINT_AT_NE';
$spell_target[ 83] = 'TARGET_POINT_AT_NW';
$spell_target[ 84] = 'TARGET_POINT_AT_SE';
$spell_target[ 85] = 'TARGET_POINT_AT_SW';
$spell_target[ 86] = 'TARGET_RANDOM_NEARBY_DEST';
$spell_target[ 87] = 'TARGET_SELF2';
$spell_target[ 89] = 'TARGET_DIRECTLY_FORWARD';
$spell_target[ 90] = 'TARGET_NONCOMBAT_PET';
$spell_target[104] = 'TARGET_IN_FRONT_OF_CASTER_30';

// Spell Auras
$spell_aura[  0] = 'SPELL_AURA_NONE';
$spell_aura[  1] = 'SPELL_AURA_BIND_SIGHT';
$spell_aura[  2] = 'SPELL_AURA_MOD_POSSESS';
$spell_aura[  3] = 'SPELL_AURA_PERIODIC_DAMAGE';
$spell_aura[  4] = 'SPELL_AURA_DUMMY';
$spell_aura[  5] = 'SPELL_AURA_MOD_CONFUSE';
$spell_aura[  6] = 'SPELL_AURA_MOD_CHARM';
$spell_aura[  7] = 'SPELL_AURA_MOD_FEAR';
$spell_aura[  8] = 'SPELL_AURA_PERIODIC_HEAL';
$spell_aura[  9] = 'SPELL_AURA_MOD_ATTACKSPEED';
$spell_aura[ 10] = 'SPELL_AURA_MOD_THREAT';
$spell_aura[ 11] = 'SPELL_AURA_MOD_TAUNT';
$spell_aura[ 12] = 'SPELL_AURA_MOD_STUN';
$spell_aura[ 13] = 'SPELL_AURA_MOD_DAMAGE_DONE';
$spell_aura[ 14] = 'SPELL_AURA_MOD_DAMAGE_TAKEN';
$spell_aura[ 15] = 'SPELL_AURA_DAMAGE_SHIELD';
$spell_aura[ 16] = 'SPELL_AURA_MOD_STEALTH';
$spell_aura[ 17] = 'SPELL_AURA_MOD_STEALTH_DETECT';
$spell_aura[ 18] = 'SPELL_AURA_MOD_INVISIBILITY';
$spell_aura[ 19] = 'SPELL_AURA_MOD_INVISIBILITY_DETECTION';
$spell_aura[ 20] = 'SPELL_AURA_OBS_MOD_HEALTH';
$spell_aura[ 21] = 'SPELL_AURA_OBS_MOD_MANA';
$spell_aura[ 22] = 'SPELL_AURA_MOD_RESISTANCE';
$spell_aura[ 23] = 'SPELL_AURA_PERIODIC_TRIGGER_SPELL';
$spell_aura[ 24] = 'SPELL_AURA_PERIODIC_ENERGIZE';
$spell_aura[ 25] = 'SPELL_AURA_MOD_PACIFY';
$spell_aura[ 26] = 'SPELL_AURA_MOD_ROOT';
$spell_aura[ 27] = 'SPELL_AURA_MOD_SILENCE';
$spell_aura[ 28] = 'SPELL_AURA_REFLECT_SPELLS';
$spell_aura[ 29] = 'SPELL_AURA_MOD_STAT';
$spell_aura[ 30] = 'SPELL_AURA_MOD_SKILL';
$spell_aura[ 31] = 'SPELL_AURA_MOD_INCREASE_SPEED';
$spell_aura[ 32] = 'SPELL_AURA_MOD_INCREASE_MOUNTED_SPEED';
$spell_aura[ 33] = 'SPELL_AURA_MOD_DECREASE_SPEED';
$spell_aura[ 34] = 'SPELL_AURA_MOD_INCREASE_HEALTH';
$spell_aura[ 35] = 'SPELL_AURA_MOD_INCREASE_ENERGY';
$spell_aura[ 36] = 'SPELL_AURA_MOD_SHAPESHIFT';
$spell_aura[ 37] = 'SPELL_AURA_EFFECT_IMMUNITY';
$spell_aura[ 38] = 'SPELL_AURA_STATE_IMMUNITY';
$spell_aura[ 39] = 'SPELL_AURA_SCHOOL_IMMUNITY';
$spell_aura[ 40] = 'SPELL_AURA_DAMAGE_IMMUNITY';
$spell_aura[ 41] = 'SPELL_AURA_DISPEL_IMMUNITY';
$spell_aura[ 42] = 'SPELL_AURA_PROC_TRIGGER_SPELL';
$spell_aura[ 43] = 'SPELL_AURA_PROC_TRIGGER_DAMAGE';
$spell_aura[ 44] = 'SPELL_AURA_TRACK_CREATURES';
$spell_aura[ 45] = 'SPELL_AURA_TRACK_RESOURCES';
$spell_aura[ 46] = 'SPELL_AURA_46';
$spell_aura[ 47] = 'SPELL_AURA_MOD_PARRY_PERCENT';
$spell_aura[ 48] = 'SPELL_AURA_48';
$spell_aura[ 49] = 'SPELL_AURA_MOD_DODGE_PERCENT';
$spell_aura[ 50] = 'SPELL_AURA_MOD_CRITICAL_HEALING_AMOUNT';
$spell_aura[ 51] = 'SPELL_AURA_MOD_BLOCK_PERCENT';
$spell_aura[ 52] = 'SPELL_AURA_MOD_CRIT_PERCENT';
$spell_aura[ 53] = 'SPELL_AURA_PERIODIC_LEECH';
$spell_aura[ 54] = 'SPELL_AURA_MOD_HIT_CHANCE';
$spell_aura[ 55] = 'SPELL_AURA_MOD_SPELL_HIT_CHANCE';
$spell_aura[ 56] = 'SPELL_AURA_TRANSFORM';
$spell_aura[ 57] = 'SPELL_AURA_MOD_SPELL_CRIT_CHANCE';
$spell_aura[ 58] = 'SPELL_AURA_MOD_INCREASE_SWIM_SPEED';
$spell_aura[ 59] = 'SPELL_AURA_MOD_DAMAGE_DONE_CREATURE';
$spell_aura[ 60] = 'SPELL_AURA_MOD_PACIFY_SILENCE';
$spell_aura[ 61] = 'SPELL_AURA_MOD_SCALE';
$spell_aura[ 62] = 'SPELL_AURA_PERIODIC_HEALTH_FUNNEL';
$spell_aura[ 63] = 'SPELL_AURA_63';
$spell_aura[ 64] = 'SPELL_AURA_PERIODIC_MANA_LEECH';
$spell_aura[ 65] = 'SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK';
$spell_aura[ 66] = 'SPELL_AURA_FEIGN_DEATH';
$spell_aura[ 67] = 'SPELL_AURA_MOD_DISARM';
$spell_aura[ 68] = 'SPELL_AURA_MOD_STALKED';
$spell_aura[ 69] = 'SPELL_AURA_SCHOOL_ABSORB';
$spell_aura[ 70] = 'SPELL_AURA_EXTRA_ATTACKS';
$spell_aura[ 71] = 'SPELL_AURA_MOD_SPELL_CRIT_CHANCE_SCHOOL';
$spell_aura[ 72] = 'SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT';
$spell_aura[ 73] = 'SPELL_AURA_MOD_POWER_COST_SCHOOL';
$spell_aura[ 74] = 'SPELL_AURA_REFLECT_SPELLS_SCHOOL';
$spell_aura[ 75] = 'SPELL_AURA_MOD_LANGUAGE';
$spell_aura[ 76] = 'SPELL_AURA_FAR_SIGHT';
$spell_aura[ 77] = 'SPELL_AURA_MECHANIC_IMMUNITY';
$spell_aura[ 78] = 'SPELL_AURA_MOUNTED';
$spell_aura[ 79] = 'SPELL_AURA_MOD_DAMAGE_PERCENT_DONE';
$spell_aura[ 80] = 'SPELL_AURA_MOD_PERCENT_STAT';
$spell_aura[ 81] = 'SPELL_AURA_SPLIT_DAMAGE_PCT';
$spell_aura[ 82] = 'SPELL_AURA_WATER_BREATHING';
$spell_aura[ 83] = 'SPELL_AURA_MOD_BASE_RESISTANCE';
$spell_aura[ 84] = 'SPELL_AURA_MOD_REGEN';
$spell_aura[ 85] = 'SPELL_AURA_MOD_POWER_REGEN';
$spell_aura[ 86] = 'SPELL_AURA_CHANNEL_DEATH_ITEM';
$spell_aura[ 87] = 'SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN';
$spell_aura[ 88] = 'SPELL_AURA_MOD_HEALTH_REGEN_PERCENT';
$spell_aura[ 89] = 'SPELL_AURA_PERIODIC_DAMAGE_PERCENT';
$spell_aura[ 90] = 'SPELL_AURA_90';
$spell_aura[ 91] = 'SPELL_AURA_MOD_DETECT_RANGE';
$spell_aura[ 92] = 'SPELL_AURA_PREVENTS_FLEEING';
$spell_aura[ 93] = 'SPELL_AURA_MOD_UNATTACKABLE';
$spell_aura[ 94] = 'SPELL_AURA_INTERRUPT_REGEN';
$spell_aura[ 95] = 'SPELL_AURA_GHOST';
$spell_aura[ 96] = 'SPELL_AURA_SPELL_MAGNET';
$spell_aura[ 97] = 'SPELL_AURA_MANA_SHIELD';
$spell_aura[ 98] = 'SPELL_AURA_MOD_SKILL_TALENT';
$spell_aura[ 99] = 'SPELL_AURA_MOD_ATTACK_POWER';
$spell_aura[100] = 'SPELL_AURA_AURAS_VISIBLE';
$spell_aura[101] = 'SPELL_AURA_MOD_RESISTANCE_PCT';
$spell_aura[102] = 'SPELL_AURA_MOD_MELEE_ATTACK_POWER_VERSUS';
$spell_aura[103] = 'SPELL_AURA_MOD_TOTAL_THREAT';
$spell_aura[104] = 'SPELL_AURA_WATER_WALK';
$spell_aura[105] = 'SPELL_AURA_FEATHER_FALL';
$spell_aura[106] = 'SPELL_AURA_HOVER';
$spell_aura[107] = 'SPELL_AURA_ADD_FLAT_MODIFIER';
$spell_aura[108] = 'SPELL_AURA_ADD_PCT_MODIFIER';
$spell_aura[109] = 'SPELL_AURA_ADD_TARGET_TRIGGER';
$spell_aura[110] = 'SPELL_AURA_MOD_POWER_REGEN_PERCENT';
$spell_aura[111] = 'SPELL_AURA_ADD_CASTER_HIT_TRIGGER';
$spell_aura[112] = 'SPELL_AURA_OVERRIDE_CLASS_SCRIPTS';
$spell_aura[113] = 'SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN';
$spell_aura[114] = 'SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN_PCT';
$spell_aura[115] = 'SPELL_AURA_MOD_HEALING';
$spell_aura[116] = 'SPELL_AURA_MOD_REGEN_DURING_COMBAT';
$spell_aura[117] = 'SPELL_AURA_MOD_MECHANIC_RESISTANCE';
$spell_aura[118] = 'SPELL_AURA_MOD_HEALING_PCT';
$spell_aura[119] = 'SPELL_AURA_119';
$spell_aura[120] = 'SPELL_AURA_UNTRACKABLE';
$spell_aura[121] = 'SPELL_AURA_EMPATHY';
$spell_aura[122] = 'SPELL_AURA_MOD_OFFHAND_DAMAGE_PCT';
$spell_aura[123] = 'SPELL_AURA_MOD_TARGET_RESISTANCE';
$spell_aura[124] = 'SPELL_AURA_MOD_RANGED_ATTACK_POWER';
$spell_aura[125] = 'SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN';
$spell_aura[126] = 'SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN_PCT';
$spell_aura[127] = 'SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS';
$spell_aura[128] = 'SPELL_AURA_MOD_POSSESS_PET';
$spell_aura[129] = 'SPELL_AURA_MOD_SPEED_ALWAYS';
$spell_aura[130] = 'SPELL_AURA_MOD_MOUNTED_SPEED_ALWAYS';
$spell_aura[131] = 'SPELL_AURA_MOD_RANGED_ATTACK_POWER_VERSUS';
$spell_aura[132] = 'SPELL_AURA_MOD_INCREASE_ENERGY_PERCENT';
$spell_aura[133] = 'SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT';
$spell_aura[134] = 'SPELL_AURA_MOD_MANA_REGEN_INTERRUPT';
$spell_aura[135] = 'SPELL_AURA_MOD_HEALING_DONE';
$spell_aura[136] = 'SPELL_AURA_MOD_HEALING_DONE_PERCENT';
$spell_aura[137] = 'SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE';
$spell_aura[138] = 'SPELL_AURA_MOD_MELEE_HASTE';
$spell_aura[139] = 'SPELL_AURA_FORCE_REACTION';
$spell_aura[140] = 'SPELL_AURA_MOD_RANGED_HASTE';
$spell_aura[141] = 'SPELL_AURA_MOD_RANGED_AMMO_HASTE';
$spell_aura[142] = 'SPELL_AURA_MOD_BASE_RESISTANCE_PCT';
$spell_aura[143] = 'SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE';
$spell_aura[144] = 'SPELL_AURA_SAFE_FALL';
$spell_aura[145] = 'SPELL_AURA_MOD_PET_TALENT_POINTS';
$spell_aura[146] = 'SPELL_AURA_ALLOW_TAME_PET_TYPE';
$spell_aura[147] = 'SPELL_AURA_MECHANIC_IMMUNITY_MASK';
$spell_aura[148] = 'SPELL_AURA_RETAIN_COMBO_POINTS';
$spell_aura[149] = 'SPELL_AURA_REDUCE_PUSHBACK';
$spell_aura[150] = 'SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT';
$spell_aura[151] = 'SPELL_AURA_TRACK_STEALTHED';
$spell_aura[152] = 'SPELL_AURA_MOD_DETECTED_RANGE';
$spell_aura[153] = 'SPELL_AURA_SPLIT_DAMAGE_FLAT';
$spell_aura[154] = 'SPELL_AURA_MOD_STEALTH_LEVEL';
$spell_aura[155] = 'SPELL_AURA_MOD_WATER_BREATHING';
$spell_aura[156] = 'SPELL_AURA_MOD_REPUTATION_GAIN';
$spell_aura[157] = 'SPELL_AURA_PET_DAMAGE_MULTI';
$spell_aura[158] = 'SPELL_AURA_MOD_SHIELD_BLOCKVALUE';
$spell_aura[159] = 'SPELL_AURA_NO_PVP_CREDIT';
$spell_aura[160] = 'SPELL_AURA_MOD_AOE_AVOIDANCE';
$spell_aura[161] = 'SPELL_AURA_MOD_HEALTH_REGEN_IN_COMBAT';
$spell_aura[162] = 'SPELL_AURA_POWER_BURN_MANA';
$spell_aura[163] = 'SPELL_AURA_MOD_CRIT_DAMAGE_BONUS';
$spell_aura[164] = 'SPELL_AURA_164';
$spell_aura[165] = 'SPELL_AURA_MELEE_ATTACK_POWER_ATTACKER_BONUS';
$spell_aura[166] = 'SPELL_AURA_MOD_ATTACK_POWER_PCT';
$spell_aura[167] = 'SPELL_AURA_MOD_RANGED_ATTACK_POWER_PCT';
$spell_aura[168] = 'SPELL_AURA_MOD_DAMAGE_DONE_VERSUS';
$spell_aura[169] = 'SPELL_AURA_MOD_CRIT_PERCENT_VERSUS';
$spell_aura[170] = 'SPELL_AURA_DETECT_AMORE';
$spell_aura[171] = 'SPELL_AURA_MOD_SPEED_NOT_STACK';
$spell_aura[172] = 'SPELL_AURA_MOD_MOUNTED_SPEED_NOT_STACK';
$spell_aura[173] = 'SPELL_AURA_173';
$spell_aura[174] = 'SPELL_AURA_MOD_SPELL_DAMAGE_OF_STAT_PERCENT';
$spell_aura[175] = 'SPELL_AURA_MOD_SPELL_HEALING_OF_STAT_PERCENT';
$spell_aura[176] = 'SPELL_AURA_SPIRIT_OF_REDEMPTION';
$spell_aura[177] = 'SPELL_AURA_AOE_CHARM';
$spell_aura[178] = 'SPELL_AURA_MOD_DEBUFF_RESISTANCE';
$spell_aura[179] = 'SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_CHANCE';
$spell_aura[180] = 'SPELL_AURA_MOD_FLAT_SPELL_DAMAGE_VERSUS';
$spell_aura[181] = 'SPELL_AURA_181';
$spell_aura[182] = 'SPELL_AURA_MOD_RESISTANCE_OF_STAT_PERCENT';
$spell_aura[183] = 'SPELL_AURA_MOD_CRITICAL_THREAT';
$spell_aura[184] = 'SPELL_AURA_MOD_ATTACKER_MELEE_HIT_CHANCE';
$spell_aura[185] = 'SPELL_AURA_MOD_ATTACKER_RANGED_HIT_CHANCE';
$spell_aura[186] = 'SPELL_AURA_MOD_ATTACKER_SPELL_HIT_CHANCE';
$spell_aura[187] = 'SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_CHANCE';
$spell_aura[188] = 'SPELL_AURA_MOD_ATTACKER_RANGED_CRIT_CHANCE';
$spell_aura[189] = 'SPELL_AURA_MOD_RATING';
$spell_aura[190] = 'SPELL_AURA_MOD_FACTION_REPUTATION_GAIN';
$spell_aura[191] = 'SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED';
$spell_aura[192] = 'SPELL_AURA_MOD_MELEE_RANGED_HASTE';
$spell_aura[193] = 'SPELL_AURA_HASTE_ALL';
$spell_aura[194] = 'SPELL_AURA_MOD_IGNORE_ABSORB_SCHOOL';
$spell_aura[195] = 'SPELL_AURA_MOD_IGNORE_ABSORB_FOR_SPELL';
$spell_aura[196] = 'SPELL_AURA_MOD_COOLDOWN';
$spell_aura[197] = 'SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE';
$spell_aura[198] = 'SPELL_AURA_198';
$spell_aura[199] = 'SPELL_AURA_MOD_INCREASES_SPELL_PCT_TO_HIT';
$spell_aura[200] = 'SPELL_AURA_MOD_KILL_XP_PCT';
$spell_aura[201] = 'SPELL_AURA_FLY';
$spell_aura[202] = 'SPELL_AURA_IGNORE_COMBAT_RESULT';
$spell_aura[203] = 'SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_DAMAGE';
$spell_aura[204] = 'SPELL_AURA_MOD_ATTACKER_RANGED_CRIT_DAMAGE';
$spell_aura[205] = 'SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_DAMAGE';
$spell_aura[206] = 'SPELL_AURA_MOD_FLIGHT_SPEED';
$spell_aura[207] = 'SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED';
$spell_aura[208] = 'SPELL_AURA_MOD_FLIGHT_SPEED_STACKING';
$spell_aura[209] = 'SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED_STACKING';
$spell_aura[210] = 'SPELL_AURA_MOD_FLIGHT_SPEED_NOT_STACKING';
$spell_aura[211] = 'SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED_NOT_STACKING';
$spell_aura[212] = 'SPELL_AURA_MOD_RANGED_ATTACK_POWER_OF_STAT_PERCENT';
$spell_aura[213] = 'SPELL_AURA_MOD_RAGE_FROM_DAMAGE_DEALT';
$spell_aura[214] = 'SPELL_AURA_214';
$spell_aura[215] = 'SPELL_AURA_ARENA_PREPARATION';
$spell_aura[216] = 'SPELL_AURA_HASTE_SPELLS';
$spell_aura[217] = 'SPELL_AURA_217';
$spell_aura[218] = 'SPELL_AURA_HASTE_RANGED';
$spell_aura[219] = 'SPELL_AURA_MOD_MANA_REGEN_FROM_STAT';
$spell_aura[220] = 'SPELL_AURA_MOD_RATING_FROM_STAT';
$spell_aura[221] = 'SPELL_AURA_221';
$spell_aura[222] = 'SPELL_AURA_222';
$spell_aura[223] = 'SPELL_AURA_223';
$spell_aura[224] = 'SPELL_AURA_224';
$spell_aura[225] = 'SPELL_AURA_PRAYER_OF_MENDING';
$spell_aura[226] = 'SPELL_AURA_PERIODIC_DUMMY';
$spell_aura[227] = 'SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE';
$spell_aura[228] = 'SPELL_AURA_DETECT_STEALTH';
$spell_aura[229] = 'SPELL_AURA_MOD_AOE_DAMAGE_AVOIDANCE';
$spell_aura[230] = 'SPELL_AURA_230';
$spell_aura[231] = 'SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE';
$spell_aura[232] = 'SPELL_AURA_MECHANIC_DURATION_MOD';
$spell_aura[233] = 'SPELL_AURA_233';
$spell_aura[234] = 'SPELL_AURA_MECHANIC_DURATION_MOD_NOT_STACK';
$spell_aura[235] = 'SPELL_AURA_MOD_DISPEL_RESIST';
$spell_aura[236] = 'SPELL_AURA_CONTROL_VEHICLE';
$spell_aura[237] = 'SPELL_AURA_MOD_SPELL_DAMAGE_OF_ATTACK_POWER';
$spell_aura[238] = 'SPELL_AURA_MOD_SPELL_HEALING_OF_ATTACK_POWER';
$spell_aura[239] = 'SPELL_AURA_MOD_SCALE_2';
$spell_aura[240] = 'SPELL_AURA_MOD_EXPERTISE';
$spell_aura[241] = 'SPELL_AURA_FORCE_MOVE_FORWARD';
$spell_aura[242] = 'SPELL_AURA_MOD_SPELL_DAMAGE_FROM_HEALING';
$spell_aura[243] = 'SPELL_AURA_243';
$spell_aura[244] = 'SPELL_AURA_COMPREHEND_LANGUAGE';
$spell_aura[245] = 'SPELL_AURA_MOD_DURATION_OF_MAGIC_EFFECTS';
$spell_aura[246] = 'SPELL_AURA_MOD_DURATION_OF_EFFECTS_BY_DISPEL';
$spell_aura[247] = 'SPELL_AURA_247';
$spell_aura[248] = 'SPELL_AURA_MOD_COMBAT_RESULT_CHANCE';
$spell_aura[249] = 'SPELL_AURA_CONVERT_RUNE';
$spell_aura[250] = 'SPELL_AURA_MOD_INCREASE_HEALTH_2';
$spell_aura[251] = 'SPELL_AURA_MOD_ENEMY_DODGE';
$spell_aura[252] = 'SPELL_AURA_SLOW_ALL';
$spell_aura[253] = 'SPELL_AURA_MOD_BLOCK_CRIT_CHANCE';
$spell_aura[254] = 'SPELL_AURA_MOD_DISARM_SHIELD';
$spell_aura[255] = 'SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT';
$spell_aura[256] = 'SPELL_AURA_NO_REAGENT_USE';
$spell_aura[257] = 'SPELL_AURA_MOD_TARGET_RESIST_BY_SPELL_CLASS';
$spell_aura[258] = 'SPELL_AURA_258';
$spell_aura[259] = 'SPELL_AURA_MOD_PERIODIC_HEAL';
$spell_aura[260] = 'SPELL_AURA_SCREEN_EFFECT';
$spell_aura[261] = 'SPELL_AURA_PHASE';
$spell_aura[262] = 'SPELL_AURA_IGNORE_UNIT_STATE';
$spell_aura[263] = 'SPELL_AURA_ALLOW_ONLY_ABILITY';
$spell_aura[264] = 'SPELL_AURA_264';
$spell_aura[265] = 'SPELL_AURA_265';
$spell_aura[266] = 'SPELL_AURA_266';
$spell_aura[267] = 'SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL';
$spell_aura[268] = 'SPELL_AURA_MOD_ATTACK_POWER_OF_STAT_PERCENT';
$spell_aura[269] = 'SPELL_AURA_MOD_IGNORE_DAMAGE_REDUCTION_SCHOOL';
$spell_aura[270] = 'SPELL_AURA_MOD_IGNORE_TARGET_RESIST';
$spell_aura[271] = 'SPELL_AURA_MOD_DAMAGE_FROM_CASTER';
$spell_aura[272] = 'SPELL_AURA_MAELSTROM_WEAPON';
$spell_aura[273] = 'SPELL_AURA_X_RAY';
$spell_aura[274] = 'SPELL_AURA_274';
$spell_aura[275] = 'SPELL_AURA_MOD_IGNORE_SHAPESHIFT';
$spell_aura[276] = 'SPELL_AURA_276';
$spell_aura[277] = 'SPELL_AURA_MOD_MAX_AFFECTED_TARGETS';
$spell_aura[278] = 'SPELL_AURA_MOD_DISARM_RANGED';
$spell_aura[279] = 'SPELL_AURA_279';
$spell_aura[280] = 'SPELL_AURA_MOD_TARGET_ARMOR_PCT';
$spell_aura[281] = 'SPELL_AURA_MOD_HONOR_GAIN';
$spell_aura[282] = 'SPELL_AURA_MOD_BASE_HEALTH_PCT';
$spell_aura[283] = 'SPELL_AURA_MOD_HEALING_RECEIVED';
$spell_aura[284] = 'SPELL_AURA_LINKED';
$spell_aura[285] = 'SPELL_AURA_MOD_ATTACK_POWER_OF_ARMOR';
$spell_aura[286] = 'SPELL_AURA_ABILITY_PERIODIC_CRIT';
$spell_aura[287] = 'SPELL_AURA_DEFLECT_SPELLS';
$spell_aura[288] = 'SPELL_AURA_288';
$spell_aura[289] = 'SPELL_AURA_289';
$spell_aura[290] = 'SPELL_AURA_MOD_ALL_CRIT_CHANCE';
$spell_aura[291] = 'SPELL_AURA_MOD_QUEST_XP_PCT';
$spell_aura[292] = 'SPELL_AURA_OPEN_STABLE';
$spell_aura[293] = 'SPELL_AURA_ADD_MECHANIC_ABILITIES';
$spell_aura[294] = 'SPELL_AURA_294';
$spell_aura[295] = 'SPELL_AURA_295';
$spell_aura[296] = 'SPELL_AURA_296';
$spell_aura[297] = 'SPELL_AURA_297';
$spell_aura[298] = 'SPELL_AURA_298';
$spell_aura[299] = 'SPELL_AURA_299';
$spell_aura[300] = 'SPELL_AURA_300';
$spell_aura[301] = 'SPELL_AURA_HEAL_ABSORB';
$spell_aura[302] = 'SPELL_AURA_302';
$spell_aura[303] = 'SPELL_AURA_MOD_DAMAGE_PCT_AURASTATE';
$spell_aura[304] = 'SPELL_AURA_304';
$spell_aura[305] = 'SPELL_AURA_MOD_MINIMUM_SPEED';
$spell_aura[306] = 'SPELL_AURA_306';
$spell_aura[307] = 'SPELL_AURA_307';
$spell_aura[308] = 'SPELL_AURA_308';
$spell_aura[309] = 'SPELL_AURA_309';
$spell_aura[310] = 'SPELL_AURA_MOD_PET_AOE_DAMAGE_AVOIDANCE';
$spell_aura[311] = 'SPELL_AURA_311';
$spell_aura[312] = 'SPELL_AURA_312';
$spell_aura[313] = 'SPELL_AURA_313';
$spell_aura[314] = 'SPELL_AURA_314';
$spell_aura[315] = 'SPELL_AURA_315';
$spell_aura[316] = 'SPELL_AURA_316';

// Spell Mods
$spell_mod[ 0] = 'SPELLMOD_DAMAGE';
$spell_mod[ 1] = 'SPELLMOD_DURATION';
$spell_mod[ 2] = 'SPELLMOD_THREAT';
$spell_mod[ 3] = 'SPELLMOD_EFFECT1';
$spell_mod[ 4] = 'SPELLMOD_CHARGES';
$spell_mod[ 5] = 'SPELLMOD_RANGE';
$spell_mod[ 6] = 'SPELLMOD_RADIUS';
$spell_mod[ 7] = 'SPELLMOD_CRITICAL_CHANCE';
$spell_mod[ 8] = 'SPELLMOD_ALL_EFFECTS';
$spell_mod[ 9] = 'SPELLMOD_NOT_LOSE_CASTING_TIME';
$spell_mod[10] = 'SPELLMOD_CASTING_TIME';
$spell_mod[11] = 'SPELLMOD_COOLDOWN';
$spell_mod[12] = 'SPELLMOD_EFFECT2';
$spell_mod[14] = 'SPELLMOD_COST';
$spell_mod[15] = 'SPELLMOD_CRIT_DAMAGE_BONUS';
$spell_mod[16] = 'SPELLMOD_RESIST_MISS_CHANCE';
$spell_mod[17] = 'SPELLMOD_JUMP_TARGETS';
$spell_mod[18] = 'SPELLMOD_CHANCE_OF_SUCCESS';
$spell_mod[19] = 'SPELLMOD_ACTIVATION_TIME';
$spell_mod[20] = 'SPELLMOD_EFFECT_PAST_FIRST';
$spell_mod[21] = 'SPELLMOD_CASTING_TIME_OLD';
$spell_mod[22] = 'SPELLMOD_DOT';
$spell_mod[23] = 'SPELLMOD_EFFECT3';
$spell_mod[24] = 'SPELLMOD_SPELL_BONUS_DAMAGE';
$spell_mod[26] = 'SPELLMOD_FREQUENCY_OF_SUCCESS';
$spell_mod[27] = 'SPELLMOD_MULTIPLE_VALUE';
$spell_mod[28] = 'SPELLMOD_RESIST_DISPEL_CHANCE';
$spell_mod[30] = 'SPELLMOD_COST_ON_HIT_FAIL';

// Summon Types
$summon_type[  41] = 'SUMMON_TYPE_CRITTER';
$summon_type[  61] = 'SUMMON_TYPE_GUARDIAN';
$summon_type[  63] = 'SUMMON_TYPE_TOTEM_SLOT1';
$summon_type[  64] = 'SUMMON_TYPE_WILD';
$summon_type[  65] = 'SUMMON_TYPE_POSESSED';
$summon_type[  66] = 'SUMMON_TYPE_DEMON';
$summon_type[  67] = 'SUMMON_TYPE_SUMMON';
$summon_type[  81] = 'SUMMON_TYPE_TOTEM_SLOT2';
$summon_type[  82] = 'SUMMON_TYPE_TOTEM_SLOT3';
$summon_type[  83] = 'SUMMON_TYPE_TOTEM_SLOT4';
$summon_type[ 121] = 'SUMMON_TYPE_TOTEM';
$summon_type[ 161] = 'SUMMON_TYPE_SIEGE';
$summon_type[ 181] = 'SUMMON_TYPE_UNKNOWN3';
$summon_type[ 187] = 'SUMMON_TYPE_UNKNOWN4';
$summon_type[ 247] = 'SUMMON_TYPE_UNKNOWN1';
$summon_type[ 287] = 'SUMMON_TYPE_FISH';
$summon_type[ 407] = 'SUMMON_TYPE_CRITTER2';
$summon_type[ 307] = 'SUMMON_TYPE_CRITTER3';
$summon_type[ 367] = 'SUMMON_TYPE_HOSTILE';
$summon_type[ 409] = 'SUMMON_TYPE_UNKNOWN5';
$summon_type[ 427] = 'SUMMON_TYPE_UNKNOWN2';
$summon_type[ 428] = 'SUMMON_TYPE_POSESSED2';
$summon_type[ 487] = 'SUMMON_TYPE_QUEST_CRITTER';
$summon_type[ 587] = 'SUMMON_TYPE_QUEST_WILD';
$summon_type[ 711] = 'SUMMON_TYPE_INFERNO';
$summon_type[ 713] = 'SUMMON_TYPE_GUARDIAN2';
$summon_type[1141] = 'SUMMON_TYPE_LIGHTWELL';
$summon_type[1161] = 'SUMMON_TYPE_FERAL_SPIRIT';
$summon_type[1302] = 'SUMMON_TYPE_CREATURE';
$summon_type[1561] = 'SUMMON_TYPE_ELEMENTAL';
$summon_type[ 429] = 'SUMMON_TYPE_RIFT';
$summon_type[1562] = 'SUMMON_TYPE_FORCE_OF_NATURE';
$summon_type[ 496] = 'SUMMON_TYPE_LAND_MINE';
$summon_type[ 628] = 'SUMMON_TYPE_HOUND';
$summon_type[ 829] = 'SUMMON_TYPE_GHOUL';
$summon_type[1021] = 'SUMMON_TYPE_IMAGE';

// Spell Family
$spell_family[ 0] = 'SPELLFAMILY_GENERIC';
$spell_family[ 1] = 'SPELLFAMILY_UNK1';
$spell_family[ 3] = 'SPELLFAMILY_MAGE';
$spell_family[ 4] = 'SPELLFAMILY_WARRIOR';
$spell_family[ 5] = 'SPELLFAMILY_WARLOCK';
$spell_family[ 6] = 'SPELLFAMILY_PRIEST';
$spell_family[ 7] = 'SPELLFAMILY_DRUID';
$spell_family[ 8] = 'SPELLFAMILY_ROGUE';
$spell_family[ 9] = 'SPELLFAMILY_HUNTER';
$spell_family[10] = 'SPELLFAMILY_PALADIN';
$spell_family[11] = 'SPELLFAMILY_SHAMAN';
$spell_family[12] = 'SPELLFAMILY_UNK2';
$spell_family[13] = 'SPELLFAMILY_POTION';
$spell_family[15] = 'SPELLFAMILY_DEATHKNIGHT';
$spell_family[17] = 'SPELLFAMILY_PET';

// Spell Schools
$spell_school[0] = 'SPELL_SCHOOL_MASK_NORMAL';
$spell_school[1] = 'SPELL_SCHOOL_MASK_HOLY';
$spell_school[2] = 'SPELL_SCHOOL_MASK_FIRE';
$spell_school[3] = 'SPELL_SCHOOL_MASK_NATURE';
$spell_school[4] = 'SPELL_SCHOOL_MASK_FROST';
$spell_school[5] = 'SPELL_SCHOOL_MASK_SHADOW';
$spell_school[6] = 'SPELL_SCHOOL_MASK_ARCANE';

// spell interrupt flags
$spell_int_flag[0] = 'SPELL_INTERRUPT_FLAG_MOVEMENT';
$spell_int_flag[1] = 'SPELL_INTERRUPT_FLAG_DAMAGE';
$spell_int_flag[2] = 'SPELL_INTERRUPT_FLAG_INTERRUPT';
$spell_int_flag[3] = 'SPELL_INTERRUPT_FLAG_AUTOATTACK';
$spell_int_flag[4] = 'SPELL_INTERRUPT_FLAG_ABORT_ON_DMG';
$spell_int_flag[5] = 'SPELL_INTERRUPT_FLAG_UNK5';

// aura interrupt flags
$aura_int_flag[ 0] = 'AURA_INTERRUPT_FLAG_UNK0';
$aura_int_flag[ 1] = 'AURA_INTERRUPT_FLAG_DAMAGE';
$aura_int_flag[ 2] = 'AURA_INTERRUPT_FLAG_UNK2';
$aura_int_flag[ 3] = 'AURA_INTERRUPT_FLAG_MOVE';
$aura_int_flag[ 4] = 'AURA_INTERRUPT_FLAG_TURNING';
$aura_int_flag[ 5] = 'AURA_INTERRUPT_FLAG_ENTER_COMBAT';
$aura_int_flag[ 6] = 'AURA_INTERRUPT_FLAG_NOT_MOUNTED';
$aura_int_flag[ 7] = 'AURA_INTERRUPT_FLAG_NOT_ABOVEWATER';
$aura_int_flag[ 8] = 'AURA_INTERRUPT_FLAG_NOT_UNDERWATER';
$aura_int_flag[ 9] = 'AURA_INTERRUPT_FLAG_NOT_SHEATHED';
$aura_int_flag[10] = 'AURA_INTERRUPT_FLAG_UNK10';
$aura_int_flag[11] = 'AURA_INTERRUPT_FLAG_UNK11';
$aura_int_flag[12] = 'AURA_INTERRUPT_FLAG_UNK12';
$aura_int_flag[13] = 'AURA_INTERRUPT_FLAG_UNK13';
$aura_int_flag[14] = 'AURA_INTERRUPT_FLAG_UNK14';
$aura_int_flag[15] = 'AURA_INTERRUPT_FLAG_UNK15';
$aura_int_flag[16] = 'AURA_INTERRUPT_FLAG_UNK16';
$aura_int_flag[17] = 'AURA_INTERRUPT_FLAG_MOUNTING';
$aura_int_flag[18] = 'AURA_INTERRUPT_FLAG_NOT_SEATED';
$aura_int_flag[19] = 'AURA_INTERRUPT_FLAG_CHANGE_MAP';
$aura_int_flag[20] = 'AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION';
$aura_int_flag[21] = 'AURA_INTERRUPT_FLAG_UNK21';
$aura_int_flag[22] = 'AURA_INTERRUPT_FLAG_UNK22';
$aura_int_flag[23] = 'AURA_INTERRUPT_FLAG_ENTER_PVP_COMBAT';
$aura_int_flag[24] = 'AURA_INTERRUPT_FLAG_DIRECT_DAMAGE';
$aura_int_flag[25] = 'AURA_INTERRUPT_FLAG_UNK25';
$aura_int_flag[26] = 'AURA_INTERRUPT_FLAG_UNK26';
$aura_int_flag[27] = 'AURA_INTERRUPT_FLAG_UNK27';
$aura_int_flag[28] = 'AURA_INTERRUPT_FLAG_UNK28';
$aura_int_flag[29] = 'AURA_INTERRUPT_FLAG_UNK29';
$aura_int_flag[30] = 'AURA_INTERRUPT_FLAG_UNK30';
$aura_int_flag[31] = 'AURA_INTERRUPT_FLAG_UNK31';

// channel interrupt flags
$chann_int_flag[ 0] = 'CHANNEL_FLAG_UNK0';
$chann_int_flag[ 1] = 'CHANNEL_FLAG_DAMAGE';
$chann_int_flag[ 2] = 'CHANNEL_FLAG_UNK2';
$chann_int_flag[ 3] = 'CHANNEL_FLAG_MOVEMENT';
$chann_int_flag[ 4] = 'CHANNEL_FLAG_TURNING';
$chann_int_flag[ 5] = 'CHANNEL_FLAG_UNK5';
$chann_int_flag[ 6] = 'CHANNEL_FLAG_UNK6';
$chann_int_flag[ 7] = 'CHANNEL_FLAG_DAMAGE2';
$chann_int_flag[ 8] = 'CHANNEL_FLAG_UNK8';
$chann_int_flag[ 9] = 'CHANNEL_FLAG_UNK9';
$chann_int_flag[10] = 'CHANNEL_FLAG_UNK10';
$chann_int_flag[11] = 'CHANNEL_FLAG_UNK11';
$chann_int_flag[12] = 'CHANNEL_FLAG_UNK12';
$chann_int_flag[13] = 'CHANNEL_FLAG_UNK13';
$chann_int_flag[14] = 'CHANNEL_FLAG_DELAY';
$chann_int_flag[15] = 'CHANNEL_FLAG_UNK15';

// damage class
$damage_class[0] = 'SPELL_DAMAGE_CLASS_NONE';
$damage_class[1] = 'SPELL_DAMAGE_CLASS_MAGIC';
$damage_class[2] = 'SPELL_DAMAGE_CLASS_MELEE';
$damage_class[3] = 'SPELL_DAMAGE_CLASS_RANGED';

// prevention type
$prevention_type[0] = 'SPELL_PREVENTION_TYPE_NONE';
$prevention_type[1] = 'SPELL_PREVENTION_TYPE_SILENCE';
$prevention_type[2] = 'SPELL_PREVENTION_TYPE_PACIFY';
